export default {
  USD: {
    curr: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    order: 1,
  },
  EUR: {
    curr: 'EUR',
    currencyName: 'European Euro',
    currencySymbol: '€',
    order: 2,
  },
  JPY: {
    curr: 'JPY',
    currencyName: 'Japanese yen',
    currencySymbol: '¥',
    order: 3,
  },
  GBP: {
    curr: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
    order: 4,
  },
  AUD: {
    curr: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
    order: 5,
  },
  CAD: {
    curr: 'CAD',
    currencyName: 'Canadian dollar',
    currencySymbol: '$',
    order: 6,
  },
  CHF: {
    curr: 'CHF',
    currencyName: 'Swiss franc',
    currencySymbol: 'Fr.',
    order: 7,
  },
  CNY: {
    curr: 'CNY',
    currencyName: 'Chinese Yuan (RenMinBi, RMB)',
    currencySymbol: '¥',
    order: 8,
  },
  MXN: {
    curr: 'MXN',
    currencyName: 'Mexican peso',
    currencySymbol: '$',
    order: 9,
  },
  SEK: {
    curr: 'SEK',
    currencyName: 'Swedish krona',
    currencySymbol: 'kr',
    order: 10,
  },
  NZD: {
    curr: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
    order: 11,
  },
  SGD: {
    curr: 'SGD',
    currencyName: 'Singapore dollar',
    currencySymbol: '$',
    order: 12,
  },
  HKD: {
    curr: 'HKD',
    currencyName: 'Hong Kong dollar',
    currencySymbol: '$',
    order: 13,
  },
  NOK: {
    curr: 'NOK',
    currencyName: 'Norwegian krone',
    currencySymbol: 'kr',
    order: 14,
  },
  AFN: {
    curr: 'AFN',
    currencyName: 'Afghan afghani',
    currencySymbol: '؋',
    order: 15,
  },
  ALL: {
    curr: 'ALL',
    currencyName: 'Albanian lek',
    currencySymbol: 'Lek',
    order: 16,
  },
  ANG: {
    curr: 'ANG',
    currencyName: 'Netherlands Antillean gulden',
    currencySymbol: 'ƒ',
    order: 17,
  },
  ARS: {
    curr: 'ARS',
    currencyName: 'Argentine peso',
    currencySymbol: '$',
    order: 18,
  },
  AWG: {
    curr: 'AWG',
    currencyName: 'Aruban florin',
    currencySymbol: 'ƒ',
    order: 19,
  },
  AZN: {
    curr: 'AZN',
    currencyName: 'Azerbaijani manat',
    currencySymbol: 'ман',
    order: 20,
  },
  BAM: {
    curr: 'BAM',
    currencyName: 'Bosnia and Herzegovina konvertibilna marka',
    currencySymbol: 'KM',
    order: 21,
  },
  BBD: {
    curr: 'BBD',
    currencyName: 'Barbadian dollar',
    currencySymbol: '$',
    order: 22,
  },
  BGN: {
    curr: 'BGN',
    currencyName: 'Bulgarian lev',
    currencySymbol: 'лв',
    order: 23,
  },
  BND: {
    curr: 'BND',
    currencyName: 'Brunei dollar',
    currencySymbol: '$',
    order: 24,
  },
  BOB: {
    curr: 'BOB',
    currencyName: 'Bolivian boliviano',
    currencySymbol: '$b',
    order: 25,
  },
  BRL: {
    curr: 'BRL',
    currencyName: 'Brazilian real',
    currencySymbol: 'R$',
    order: 26,
  },
  BSD: {
    curr: 'BSD',
    currencyName: 'Bahamian dollar',
    currencySymbol: '$',
    order: 27,
  },
  BWP: {
    curr: 'BWP',
    currencyName: 'Botswana pula',
    currencySymbol: 'P',
    order: 28,
  },
  BYR: {
    curr: 'BYR',
    currencyName: 'Belarusian ruble',
    currencySymbol: 'p.',
    order: 29,
  },
  BZD: {
    curr: 'BZD',
    currencyName: 'Belize dollar',
    currencySymbol: 'BZ$',
    order: 30,
  },
  CLP: {
    curr: 'CLP',
    currencyName: 'Chilean peso',
    currencySymbol: '$',
    order: 31,
  },
  COP: {
    curr: 'COP',
    currencyName: 'Colombian peso',
    currencySymbol: '$',
    order: 32,
  },
  CRC: {
    curr: 'CRC',
    currencyName: 'Costa Rican colon',
    currencySymbol: '₡',
    order: 33,
  },
  CZK: {
    curr: 'CZK',
    currencyName: 'Czech koruna',
    currencySymbol: 'Kč',
    order: 34,
  },
  DKK: {
    curr: 'DKK',
    currencyName: 'Danish krone',
    currencySymbol: 'kr',
    order: 35,
  },
  DOP: {
    curr: 'DOP',
    currencyName: 'Dominican peso',
    currencySymbol: 'RD$',
    order: 36,
  },
  EGP: {
    curr: 'EGP',
    currencyName: 'Egyptian pound',
    currencySymbol: '£',
    order: 37,
  },
  FJD: {
    curr: 'FJD',
    currencyName: 'Fijian dollar',
    currencySymbol: '$',
    order: 38,
  },
  FKP: {
    curr: 'FKP',
    currencyName: 'Falkland Islands pound',
    currencySymbol: '£',
    order: 39,
  },
  GIP: {
    curr: 'GIP',
    currencyName: 'Gibraltar pound',
    currencySymbol: '£',
    order: 40,
  },
  GTQ: {
    curr: 'GTQ',
    currencyName: 'Guatemalan quetzal',
    currencySymbol: 'Q',
    order: 41,
  },
  GYD: {
    curr: 'GYD',
    currencyName: 'Guyanese dollar',
    currencySymbol: '$',
    order: 42,
  },
  HNL: {
    curr: 'HNL',
    currencyName: 'Honduran lempira',
    currencySymbol: 'L',
    order: 43,
  },
  HRK: {
    curr: 'HRK',
    currencyName: 'Croatian kuna',
    currencySymbol: 'kn',
    order: 44,
  },
  HUF: {
    curr: 'HUF',
    currencyName: 'Hungarian forint',
    currencySymbol: 'Ft',
    order: 45,
  },
  IDR: {
    curr: 'IDR',
    currencyName: 'Indonesian rupiah',
    currencySymbol: 'Rp',
    order: 46,
  },
  ILS: {
    curr: 'ILS',
    currencyName: 'Israeli new sheqel',
    currencySymbol: '₪',
    order: 47,
  },
  INR: {
    curr: 'INR',
    currencyName: 'Indian rupee',
    currencySymbol: '₹',
    order: 48,
  },
  IRR: {
    curr: 'IRR',
    currencyName: 'Iranian rial',
    currencySymbol: '﷼',
    order: 49,
  },
  ISK: {
    curr: 'ISK',
    currencyName: 'Icelandic króna',
    currencySymbol: 'kr',
    order: 50,
  },
  JMD: {
    curr: 'JMD',
    currencyName: 'Jamaican dollar',
    currencySymbol: 'J$',
    order: 51,
  },
  KGS: {
    curr: 'KGS',
    currencyName: 'Kyrgyzstani som',
    currencySymbol: 'лв',
    order: 52,
  },
  KHR: {
    curr: 'KHR',
    currencyName: 'Cambodian riel',
    currencySymbol: '៛',
    order: 53,
  },
  KPW: {
    curr: 'KPW',
    currencyName: 'North Korean won',
    currencySymbol: '₩',
    order: 54,
  },
  KRW: {
    curr: 'KRW',
    currencyName: 'South Korean won',
    currencySymbol: '₩',
    order: 55,
  },
  KYD: {
    curr: 'KYD',
    currencyName: 'Cayman Islands dollar',
    currencySymbol: '$',
    order: 56,
  },
  KZT: {
    curr: 'KZT',
    currencyName: 'Kazakhstani tenge',
    currencySymbol: 'лв',
    order: 57,
  },
  LAK: {
    curr: 'LAK',
    currencyName: 'Lao kip',
    currencySymbol: '₭',
    order: 58,
  },
  LBP: {
    curr: 'LBP',
    currencyName: 'Lebanese lira',
    currencySymbol: '£',
    order: 59,
  },
  LKR: {
    curr: 'LKR',
    currencyName: 'Sri Lankan rupee',
    currencySymbol: '₨',
    order: 60,
  },
  LRD: {
    curr: 'LRD',
    currencyName: 'Liberian dollar',
    currencySymbol: '$',
    order: 61,
  },
  LVL: {
    curr: 'LVL',
    currencyName: 'Latvian lats',
    currencySymbol: 'Ls',
    order: 62,
  },
  MKD: {
    curr: 'MKD',
    currencyName: 'Macedonian denar',
    currencySymbol: 'ден',
    order: 63,
  },
  MNT: {
    curr: 'MNT',
    currencyName: 'Mongolian tugrik',
    currencySymbol: '₮',
    order: 64,
  },
  MUR: {
    curr: 'MUR',
    currencyName: 'Mauritian rupee',
    currencySymbol: '₨',
    order: 65,
  },
  MYR: {
    curr: 'MYR',
    currencyName: 'Malaysian ringgit',
    currencySymbol: 'RM',
    order: 66,
  },
  NAD: {
    curr: 'NAD',
    currencyName: 'Namibian dollar',
    currencySymbol: '$',
    order: 67,
  },
  NGN: {
    curr: 'NGN',
    currencyName: 'Nigerian naira',
    currencySymbol: '₦',
    order: 68,
  },
  NIO: {
    curr: 'NIO',
    currencyName: 'Nicaraguan cordoba',
    currencySymbol: 'C$',
    order: 69,
  },
  NPR: {
    curr: 'NPR',
    currencyName: 'Nepalese rupee',
    currencySymbol: '₨',
    order: 70,
  },
  OMR: {
    curr: 'OMR',
    currencyName: 'Omani rial',
    currencySymbol: '﷼',
    order: 71,
  },
  PAB: {
    curr: 'PAB',
    currencyName: 'Panamanian balboa',
    currencySymbol: 'B/.',
    order: 72,
  },
  PEN: {
    curr: 'PEN',
    currencyName: 'Peruvian nuevo sol',
    currencySymbol: 'S/.',
    order: 73,
  },
  PHP: {
    curr: 'PHP',
    currencyName: 'Philippine peso',
    currencySymbol: '₱',
    order: 74,
  },
  PKR: {
    curr: 'PKR',
    currencyName: 'Pakistani rupee',
    currencySymbol: '₨',
    order: 75,
  },
  PLN: {
    curr: 'PLN',
    currencyName: 'Polish zloty',
    currencySymbol: 'zł',
    order: 76,
  },
  PYG: {
    curr: 'PYG',
    currencyName: 'Paraguayan guarani',
    currencySymbol: 'Gs',
    order: 77,
  },
  QAR: {
    curr: 'QAR',
    currencyName: 'Qatari riyal',
    currencySymbol: '﷼',
    order: 78,
  },
  RON: {
    curr: 'RON',
    currencyName: 'Romanian leu',
    currencySymbol: 'lei',
    order: 79,
  },
  RSD: {
    curr: 'RSD',
    currencyName: 'Serbian dinar',
    currencySymbol: 'Дин.',
    order: 80,
  },
  RUB: {
    curr: 'RUB',
    currencyName: 'Russian ruble',
    currencySymbol: 'руб',
    order: 81,
  },
  SAR: {
    curr: 'SAR',
    currencyName: 'Saudi riyal',
    currencySymbol: '﷼',
    order: 82,
  },
  SBD: {
    curr: 'SBD',
    currencyName: 'Solomon Islands dollar',
    currencySymbol: '$',
    order: 83,
  },
  SCR: {
    curr: 'SCR',
    currencyName: 'Seychellois rupee',
    currencySymbol: '₨',
    order: 84,
  },
  SHP: {
    curr: 'SHP',
    currencyName: 'Saint Helena pound',
    currencySymbol: '£',
    order: 85,
  },
  SOS: {
    curr: 'SOS',
    currencyName: 'Somali shilling',
    currencySymbol: 'S',
    order: 86,
  },
  SRD: {
    curr: 'SRD',
    currencyName: 'Surinamese dollar',
    currencySymbol: '$',
    order: 87,
  },
  SYP: {
    curr: 'SYP',
    currencyName: 'Syrian pound',
    currencySymbol: '£',
    order: 88,
  },
  THB: {
    curr: 'THB',
    currencyName: 'Thai baht',
    currencySymbol: '฿',
    order: 89,
  },
  TTD: {
    curr: 'TTD',
    currencyName: 'Trinidad and Tobago dollar',
    currencySymbol: 'TT$',
    order: 90,
  },
  TWD: {
    curr: 'TWD',
    currencyName: 'New Taiwan dollar',
    currencySymbol: 'NT$',
    order: 91,
  },
  UAH: {
    curr: 'UAH',
    currencyName: 'Ukrainian hryvnia',
    currencySymbol: '₴',
    order: 92,
  },
  UYU: {
    curr: 'UYU',
    currencyName: 'Uruguayan peso',
    currencySymbol: '$U',
    order: 93,
  },
  UZS: {
    curr: 'UZS',
    currencyName: 'Uzbekistani som',
    currencySymbol: 'лв',
    order: 94,
  },
  VND: {
    curr: 'VND',
    currencyName: 'Vietnamese dong',
    currencySymbol: '₫',
    order: 95,
  },
  YER: {
    curr: 'YER',
    currencyName: 'Yemeni rial',
    currencySymbol: '﷼',
    order: 96,
  },
  ZAR: {
    curr: 'ZAR',
    currencyName: 'South African rand',
    currencySymbol: 'R',
    order: 97,
  },
};
